name: whatsupcoder
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  google_sign_in: ^4.3.0
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  font_awesome_flutter: ^8.2.0
  timeline: ^0.0.1
  flutter_plugin_pdf_viewer: ^1.0.7
  url_launcher: ^5.4.2
  flutter_pdfview: ^1.0.1
  path_provider: ^1.6.5
  http: ^0.12.0+4
  animator: ^1.0.0+5
  timeline_list: ^0.0.5
  flutter_full_pdf_viewer: ^1.0.6
  firebase_storage: ^3.1.5
  firebase_analytics: ^5.0.11
  firebase: ^7.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img1.png
    - assets/img2.png
    - assets/img3.png
    - assets/img4.png
    - assets/img5.png
    - assets/img6.png
    - assets/img7.png
    - assets/img8.jpg
    - assets/img9.jpg
    - assets/img11.jpeg
    - assets/img12.jpg
    - assets/img13.jpg
    - assets/img14.jpg
    - assets/img15.jpg
    - assets/img18.png
    - assets/img19.png
    - assets/img22.png
    - assets/img21.jpg
    - assets/img26.png
    - assets/img27.png
    - assets/acc.png
    - assets/contacts.png
    - assets/map.png
    - assets/reg.png
    - assets/sessions.png
    - assets/stalls.png
    - assets/mypdf1.pdf
    - assets/mypdf2.pdf
    - assets/mypdf3.pdf
    - assets/mypdf4.pdf
    - assets/mypdf5.pdf
    - assets/mapimg.pdf
    - assets/isa.png




  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
